### PR TITLE
Fix v0.6 related deprecations

### PR DESCRIPTION
**Pull request by ScottPJones**
Note: this fixes the deprecations, however I noticed that there is a failure when running the unit tests (that is unrelated to my changes). (I will make an issue for that, I just wanted it clear that it wasn't cause by my v0.6 fixes)

### CODE REVIEW

**Comment by timholy** [comment]
Thanks for doing this! This seems merge-worthy as is. However, I should also point out that I simply avoid using this package on 0.6; its real purpose is to provide more flexible ranges for earlier julia versions. An example is [Unitful](https://github.com/ajkeller34/Unitful.jl/blob/8f77d038d1a7ebea8a37bf5c2c4420cdbf452034/src/Unitful.jl#L6-L8).

I'd propose that we merge this, but perhaps I should put in some kind of warning that it's not recommended on newer versions of Julia?

**Comment by ScottPJones** [comment]
Yes, I hadn't realized that this was just for previous releases, it's being used by @ChrisRackauckas' wonderful https://github.com/JuliaDiffEq/DiffEqBase.jl, which I was trying to help get deprecation free on v0.6.
A warning would be good!

**Comment by ScottPJones** [comment]
Note: I don't understand the Travis failures on v0.5.1, that runs fine when I test it on MacOS and a Linux VM. (the failures on nightly are due to the unit tests failing, which is unrelated to my changes, see issue #4

**Comment by ChrisRackauckas** [comment]
This was being used to get ranges that worked with Unitful pre-v0.6. Since it seems you fixed that in Base, luckily this is no longer needed. Thanks for the work though! Maybe something should be added to the README that this ended up getting merged to Base, along with the PR #?

**Comment by timholy** [comment]
Actually, what got merged to base was considerably more involved, but yes, very good idea. See d2783edf19805eeb7a89389e10b71499e672c36d.

**Comment by timholy** [comment]
> Note: I don't understand the Travis failures on v0.5.1, that runs fine when I test it on MacOS and a Linux VM. (the failures on nightly are due to the unit tests failing, which is unrelated to my changes, see issue #4

The issue is that the `where T` syntax is confusing the parser, which has to handle both branches even though only one will be used. You could use `include_string` if you want to hide code from the parser.

**Comment by ScottPJones** [comment]
To clarify: if code has `Ranges.linspace(...)`, will simply `linspace(...)` (i.e. with the same arguments) work in v0.6 and later?
Also, I realize it's the `where T` syntax, but I'd tried it on v0.5.1 already, and it worked OK (on my Mac), so I don't know just why the parser can't handle it on the Travis build (it's running on v0.5.2)

**Comment by timholy** [comment]
> To clarify: if code has Ranges.linspace(...), will simply linspace(...) (i.e. with the same arguments) work in v0.6 and later?

Yes, that should basically be right.

**Comment by timholy** [comment]
Scott, I don't mean to nix your hard work here, but I'm beginning to wonder whether on 0.6 this package should essentially become
```julia
module Ranges
const linspace = Base.linspace
end
```
If that's the easier route, I can submit a PR (I have one mostly ready). The downside is that there are several behavior changes for Ranges in 0.6, and so quite a few of the tests need modification.

If you're close to getting 0.6 working, then it might be better to proceed and then place an upper bound of `0.7-` on the julia version.

**Comment by ScottPJones** [comment]
No problem!  Whatever is better for users of Ranges!

It is working on v0.5.2 Linux, fails on MacOS X (simply installing Julia! not related to my change), works on v0.6.0 but a unit test fails (linspace itself gives different answers between v0.5.x and v0.6.x for `linspace(1,27,10)` which seems to make the test fail)

**Comment by timholy** [comment]
Yes, the accuracy of `linspace` has gone up in 0.6. If you want to proceed with this route, you could just make running those particular tests conditional on
```julia
const oldversion = VERSION < v"0.6.0-dev.2390"
```
In other words, I'm fine with skipping some tests as needed to get this to pass on 0.6, since this isn't something with long-term viability anyway.

**Comment by ChrisRackauckas** [comment]
The range just needs to be able to use unitful numbers to plot for that application. So simply using the v0.6 ranges will be fine.

**Comment by ScottPJones** [comment]
Ok!  All passing now, and I did put the limitation on the Julia version to `julia 0.5 0.7-`.
Hope this is mergeable now.

**Comment by timholy** [comment]
Great, many thanks!

**Comment by timholy** [comment]
New release tag submitted.

**Pull request merged**
